
server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: cap
  driud:
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000
    validation-query: select 1
    time-between-eviction-runs-millis: 60000
    test-on-borrow: false
    test-while-idle: true

mybatis:
  type-aliases-package: cn.com.gome.gsr.cap.model
  mapper-locations: classpath:mapper/*Mapper.xml
mapper:
  mappers:
    - com.betalpha.utils.CsvMapper
  not-empty: true
  identity: MYSQL

logging:
  config: classpath:logback-spring.xml